name = "backend"
compatibility_date = "2024-08-22"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNmU1ODRlOGYtMTg1MC00ZGE4LThhZmYtYjliMDU0MWFlZDNhIiwidGVuYW50X2lkIjoiYjYyYTRmY2Q3NWMyODI1YTVlMzMxOWUwYzBjOGNiNjlmOGVhYjk5YTdlN2E1YmYwZDU0MWIyZWM1YzVkMGNkNiIsImludGVybmFsX3NlY3JldCI6ImJiNzZiYTdhLTdjZDUtNGNhYy05Mjk0LThlMjcyMzE0YmE3MyJ9.vZSV0YtkH8TkgmoQQ9RTp7-2yu8DNlEH7MLAuy0kBnA"
JWT_SECRET="fnawifnawbiu2919fsf4286"
